### ISSUE TITLE
is it possible to make the widget wider?

### ISSUE THREAD

**Issue by AimPizza** [iFreilicht/spotifyd-status#1]
First up: great script, love it!
Now my question: Is it possible to make the widget a bit wider so the text doesn't always have to scroll? Another option or perhaps addition would be to truncate once the text is too long.
Another note: There is a small typo where the module is named `spotifyd` but in `modules-right` it's included as `spotify`. Sadly I am too inexperienced to create a proper pull request myself :frowning_face: :

**Comment by iFreilicht** [comment]
Hey, glad to hear it!

> Is it possible to make the widget a bit wider so the text doesn't always have to scroll?

Yes, you can make the widget wider by changing `MAX_WIDTH` in [this line here](https://github.com/iFreilicht/spotifyd-status/blob/19f6a6375f51e6d9c80fa6a08a4eeae40911673e/src/main.rs#L27) to whatever you want, and then following the installation instructions again.

> Another option or perhaps addition would be to truncate once the text is too long.

To turn off scrolling, you can [remove this line](https://github.com/iFreilicht/spotifyd-status/blob/19f6a6375f51e6d9c80fa6a08a4eeae40911673e/src/main.rs#L115).

I've thought about making both of these options, maybe I'll have a go some time this week :)

> Another note: There is a small typo where the module is named spotifyd but in modules-right it's included as spotify. 

Ah good catch! I fixed that, does it look correct to you now?

**Comment by AimPizza** [comment]
thank you very much - that works like a charm

**Comment by iFreilicht** [comment]
Great to hear! I turned these into proper features now. You can now [set SCROLL_DELAY to 0](https://github.com/iFreilicht/spotifyd-status/blob/6138ebe6a5bcb60466212cfc1695fc6747e549a3/src/main.rs#L22) to turn scrolling off, and you can [put a string into TRUNCATE_FORMAT](https://github.com/iFreilicht/spotifyd-status/blob/6138ebe6a5bcb60466212cfc1695fc6747e549a3/src/main.rs#L18) to add a string afterwards so you can see that the song title has been truncated even if it's not scrolling.

Would be cool if you could try it, and if you're happy I'll close this issue :)

**Comment by AimPizza** [comment]
This is awesome - perfect!

**Comment by iFreilicht** [comment]
Wonderful!
